# 史上最全 Vue 前端代码风格指南 [https://yuye.fun/post/d984eb1a.html]
ls:
  .dir: kebab-case | lowercase
  .js: kebab-case | camelCase
  .jsx: 'PascalCase | kebab-case | regex:^index$'
  .ts: kebab-case | camelCase
  .tsx: 'PascalCase | kebab-case | regex:^index$'
  .d.ts: kebab-case | camelCase
  .mock.ts: camelCase
  .config.js: lowercase
  .config.ts: lowercase
  .css: kebab-case
  .module.css: kebab-case
  .scss: kebab-case
  .module.scss: PascalCase | kebab-case
  .less: kebab-case
  .module.less: kebab-case
  src/pages:
    .tsx: PascalCase | kebab-case

ignore:
  - .git
  - .history
  - .husky
  - .idea
  - .vscode
  - .next
  - .swc
  - .cz-config.js
  - .env-cmdrc.js
  - .eslintrc.js
  - .stylelintrc.js
  - build
  - node_modules
  - src/vendor
